### ISSUE TITLE
ImportError: No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by Chriszat** [tkaemming/django-subdomains#75]
Calling from subdomains.utils import reverse gives the below error

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\subdomains\utils.py", line 8, in <module>
    from django.core.urlresolvers import reverse as simple_reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'

**Comment by subhajeet2107** [comment]
We are facing same issue as well, please merge the latest PR as it will this issue

**Comment by Princewill-Kelechi** [comment]
Am also facing this issue pls

**Comment by omolojakazeem** [comment]
Still facing this issue. Any headway yet?

**Comment by levkk** [comment]
Django removed this in 2.1. Package needs to be updated to support Django 2.1+.

**Comment by haradhansharma** [comment]
try:
    from django.core.urlresolvers import reverse as simple_reverse
except ImportError:
    from django.urls import resolve as simple_reverse

**Comment by haradhansharma** [comment]
`try:
    from django.core.urlresolvers import reverse as simple_reverse
except ImportError:
    from django.urls import resolve as simple_reverse`
